# Generated by Django 4.2.5 on 2023-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
