# Generated by Django 4.2.5 on 2023-10-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_custompermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcribeplam',
            name='still_valid',
            field=models.BooleanField(default=True),
        ),
    ]
